### ISSUE TITLE
Importing functions from transposon_classifier_rfsb

### ISSUE THREAD

**Issue by iliasbukraa** [DerKevinRiehl/transposon_classifier_rfsb#2]
Hi Kevin

Thanks for developing such a impressive tool!

I am in the process of developing a tool that can classify TE's as somatic and your tool seems to be perfect to implement in this process. However, my question is if there is a way to import certain functions of your tool, since it is a CL-tool. Do you have any suggestions on what the best way is (fork?), because for me the preferred way of working would be to simply import a function, instead of trying to run it in the command line through a script.

Hope to hear some of your suggestions and thanks!

**Comment by DerKevinRiehl** [comment]
Dear iliasbukraa,
sorry for the late reply, hope this message still arrives at you.

I think the best way of doing it is to copy the source (you can use a CLI tool called git to clone all source code from the online repository to your local device) copy the code to your IDE and then work with it by importing.

However, for using my code I guess you would still need something like a documentation. I suggest you read the code and comments, and if you have questions you can come back to me :-).

Examples for how to run the different methods for different modes can be found here:
https://github.com/DerKevinRiehl/transposon_classifier_rfsb/blob/main/RFSB_TE_Classifier.py
This file checks what was given in the input of the command line, and calls the internal methods accordingly, this should be most helpful for you in understanding the code.

Best regards and looking forward to your answers,
Best,
Kevin

**Comment by Ramkyeri** [comment]
Dear Kevin, 


I think this "Transposon Classifier "RFSB" can be installed in the conda environment  "(transposon_annotation_tools_env)

with regards 

Ramky
